### ISSUE TITLE
BlueBridgeGP uses a deprecated event that affects server performance

### ISSUE THREAD

**Issue by ping-localhost** [Mark-225/BlueBridge#16]
```
BlueBridgeGP vv1.3.1-alpha" has registered a listener for me.ryanhamshire.GriefPrevention.events.ClaimModifiedEvent on method "public void de.mark225.bluebridge.griefprevention.addon.listener.GriefPreventionListener.onClaimModified(me.ryanhamshire.GriefPrevention.events.ClaimModifiedEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Mark_225, Aurelien30000].
```

As requested by grief prevention, I'm opening an issue. Let me know if I can be off any help

**Comment by Mark-225** [comment]
I just checked the reason for deprecation and apparently, GriefPrevention just changed the name of the event and marked the old one as deprecated to incentivise devs to switch over, not because the old event has performance issues. I think Bukkit then just assumes it "will affect server performance", solely because it is deprecated.
I'll see if I can switch to the new event (need to maintain backwards compatibility with all Minecraft versions BlueMap supports).  Until then, you can probably just ignore that.
