### ISSUE TITLE
support for HuskTowns, Factions and other user/group/town based region claiming

### ISSUE THREAD

**Issue by embedvr** [Mark-225/BlueBridge#17]
I believe this would be great for a Towny or Factions based server. I assume this would be on a per-plugin implementation but I am willing to add support for HuskTowns (paid Towny implementation) if possible!

It also looks like this project is semi dead? Do you have any interest in continuing the project?

**Comment by Mark-225** [comment]
Yeah sure, feel free to make PRs and ask me if you need any help (preferably on Discord in DMs or the 3rd-party support channel on BlueMap. I'm Mark_225#8521 and listed as the BlueBridge developer in the plugins channel).  
  
I kinda just lost motivation to add new modules because there's so many more different ways plugins provide region APIs than I expected and my "modular" approach didn't turn out to be quite modular enough to handle all of that without changes to the core module every time... For now, the two supported plugins just work well enough so I didn't need to update anything in a while. Maybe I'll pick it back up when Bluemap v2 releases with some new features I could use.
