### ISSUE TITLE
Marker not updating

### ISSUE THREAD

**Issue by Luki2410** [Mark-225/BlueBridge#7]
When using Worldguard to define regions, a marker in the bluemap should be created after some time.
Unfortunately this is not working for the dimension "world_nether".

The console is stating, that the changes done to worldguard have been saved to background but the marker is never generated .
Using the latest version of all involved plugins:
- BlueBridge (v1.3-alpha)
- BlueMap (1.5.5)
- WorldGuard (7.0.5)
- Paper 1.16.5 (Build #779)

**Comment by Mark-225** [comment]
Thanks for the detailed info, I will try to replicate the issue once I have time.  
In the meantime, could you tell me if the marker is created when it already exists on a fresh server restart? That would tell me if it was an issue with my plugin not detecting the world at all or not fetching region updates correctly.

**Comment by Luki2410** [comment]
Thanks for your fast reply!
Sorry for missing out that information. The marker is also not created after restarting the server.

**Comment by Mark-225** [comment]
Alright so the issues were:
1. I overwrote the current markers for a region on each world update (Don't even ask how I didn't notice that WAY earlier :D)
2. I didn't reset the last saved markers on every Bluemap reload so it just cleared the markerset (which is intended) and then it thought all the old regions were unchanged and didn't add them again.

Both issues will be fixed in v1.3.1-alpha.
